<?php
	
	function topgroupdata_menu() 
	{
		$items = array();
	
		$items['topgroups/%/%/%'] = array(
			'title' => '',
			'description' => 'Get Top 100 Branches of Fylke/Kommune',
			'page callback' => 'getTopGroups',
			'page arguments' => array(3),
			'access arguments' => array('access content'), 
			'type' => MENU_CALLBACK,
		);
		
		return $items;	
	}


	function getTopGroups()
	{
		$fkId = arg(1);
		$dataYear = arg(2);
		$type = arg(3);
		
		$dataHtml = NULL;
		
		if($type == 'fylke')
			$dataHtml.= show_top_group_by_fylke_id($fkId, $dataYear);
		elseif($type == 'kommune')
			$dataHtml.= show_top_group_by_kommune_id($fkId, $dataYear);
		
		$dataHtml.= drupal_render(drupal_get_form('kommunal_data_filter_form'));
		
		return $dataHtml;		
	}
		
	

	function show_top_group_by_fylke_id($fylkeId, $dataYear)
	{
		global $base_url;
		global $user;

		$output = NULL;		
		
		db_set_active('kommunaldata');	
		
		// Get Fylke Basic Information;
		$query = db_select('fylke', 'A');
		$query->leftJoin('fylke_innbyggere', 'B', 'A.fylke_id = B.fylke_id AND B.innbygger_year ='.$dataYear);
		$query->fields('A', array('fylke_id', 'fylke_navn', 'fylke_ordforer_navn', 'fylke_parti', 'fylke_periode', 'fylke_adviser', 'fylke_telefon', 'fylke_kontaktinfo', 'fylke_kontaktinfo', 'fylke_hjemmeside', 'fylke_forretningsadr', 'fylke_forradrpostnr', 'fylke_forradrpoststed', 'fylke_postadresse', 'fylke_ppostnr', 'fylke_ppoststed' ));
		
		$query->fields('B', array('innbygger', 'fylke_group'));
		$query->condition('A.fylke_id', $fylkeId, '=');
		$fylkeData = $query->execute();
		
		db_set_active();
		
		$fylkeId = $fylkeName = $fylkeMayor = $fylkeParti = $fylkePeriod = $fylkeAdv = $fylkePhone = $fylkeEmail = $fylkeUrl = NULL;
		
		$fylkeGroup = $innbyggerTotal = 0;
		
		foreach ($fylkeData as $dataRow) 
		{
			$fylkeId = $dataRow->fylke_id;
			$fylkeName = $dataRow->fylke_navn;
			$fylkeMayor = $dataRow->fylke_ordforer_navn;
			$fylkeParti = $dataRow->fylke_parti;
			$fylkePeriod = $dataRow->fylke_periode;
			$fylkeAdv = $dataRow->fylke_adviser;
			$fylkePhone = $dataRow->fylke_telefon;
			$fylkeEmail = $dataRow->fylke_kontaktinfo;
			$fylkeUrl = $dataRow->fylke_hjemmeside;
			$innbyggerTotal = $dataRow->innbygger;
			$fylkeGroup = $dataRow->fylke_group;	
			
			$fylkeForretningsadr = $dataRow->fylke_forretningsadr;	
			$fylkeForradrpostnr = $dataRow->fylke_forradrpostnr;	
			$fylkeForradrpoststed = $dataRow->fylke_forradrpoststed;	
			$fylkePostadresse = $dataRow->fylke_postadresse;	
			$fylkePpostnr = $dataRow->fylke_ppostnr;	
			$fylkePpoststed = $dataRow->fylke_ppoststed;				

		}	
				
		$logoPath = $base_url."/sites/default/files/komlogo/".$fylkeId.".gif";

		$output.= '<div class="getUrlData">';		
		
		$output.= '<div class="right-content">';
		$output.= '	<div class="logo-widget">';
		$output.= '		<img src="'.$logoPath.'" title="'.$fylkeName.'" width="75" />';
		$output.= '		<h1>'.$fylkeName.'</h1>';
		$output.= '	</div>';

		$output.= '<h3>Offisiell informasjon</h3>';	

		$output.= '	<div class="info-box fylke-result">';
		$output.= '<a style="float: right; margin-top: -36px; margin-right: -20px;" href="#" data-toggle="tooltip" title="Fylke Kommune Information box"><i class="fa fa-question-circle"></i></a>';

		$output.= '		<div class="inner-box">';
		
		$output.= '			<label>';
		$output.= '				<span style="width:200px;"><strong>Ordf&oslash;rer:</strong></span>';
		$output.= '				<span>'.$fylkeMayor.' - '.$fylkeParti.' ( '.$fylkePeriod.' ) </span>';
		$output.= '			</label>';
		
		if($user->uid)
		{
			$output.= '			<label>';
			$output.= '				<span><strong>R&aring;dmann:</strong></span>';
			$output.= '				<span>'.$fylkeAdv.'</span>';
			$output.= '			</label>';
		}
		
		$output.= '			<label>';
		$output.= '				<span><strong>E-post:</strong></span>';
		$output.= '				<span><a href="mailto:'.$fylkeEmail.'">'.$fylkeEmail.'</a></span>';
		$output.= '			</label>';
		
		if($user->uid)
		{
			$output.= '			<label>';
			$output.= '				<span><strong>Telefon:</strong></span>';
			$output.= '				<span>'.$fylkePhone.'</span>';
			$output.= '			</label>';
		}
			
		$output.= '			<label>';
		$output.= '				<span><strong>Hjemmeside:</strong></span>';
		$output.= '				<span><a href="http://'.$fylkeUrl.'" target="_blank">'.$fylkeUrl.'</a></span>';
		$output.= '			</label>';
		
		$output.= '			<label>';
		$output.= '				<span><strong>Fylke nr:</strong></span>';
		$output.= '				<span>'.$fylkeId.'</span>';
		$output.= '			</label>';

		$output.= '			<label>';
		$output.= '				<span><strong>Innbyggere:</strong></span>';
		$output.= '				<span>'.$innbyggerTotal.' ('.$dataYear.')</span>';
		$output.= '			</label>';
		$output.= '		</div>';
		
		$output.= '		<div class="inner-box">';
		
		$output.= '			<label>';
		$output.= '				<span style="width:200px;"><strong>Forretningsadresse: </strong></span>';
		$output.= '				<span>'.$fylkeForretningsadr.'</span>';
		$output.= '			</label>';
		
		$output.= '			<label>';
		$output.= '				<span><strong>Postnr./Poststed:</strong></span>';
		$output.= '				<span>'.$fylkeForradrpostnr.' / '.$fylkeForradrpoststed.'</span>';
		$output.= '			</label>';
		
		$output.= '			<label>';
		$output.= '				<span><strong>Postadresse:</strong></span>';
		$output.= '				<span>'.$fylkePostadresse.'</span>';
		$output.= '			</label>';
		
		$output.= '			<label>';
		$output.= '				<span><strong>Postnr./Poststed:</strong></span>';
		$output.= '				<span>'.$fylkePpostnr.' / '.$fylkePpoststed.'</span>';
		$output.= '			</label>';		
		$output.= '		</div>';
		$output.= '	</div>';
		
		if($user->uid)
			$output.= getBranchesGrid($fylkeId, $dataYear, $fylkeName);
		
		$output.= '</div>';	
								
		return $output;
	
	}
	
	function show_top_group_by_kommune_id($kommuneId, $dataYear) 
	{
		global $base_url;
		global $user;

		$output = NULL;
				
		db_set_active('kommunaldata');	
		
		// Get kommune Basic Information;
		$query = db_select('kommune', 'A');
		$query->join('kommune_innbyggere', 'B', 'A.kommune_id = B.kommune_id AND B.innbygger_year ='.$dataYear);
		$query->fields('A', array('kommune_id', 'kommune_navn', 'kommune_ordforer', 'kommune_parti', 'kommune_periode', 'kommune_adviser', 'kommune_forretningsadr', '	kommune_forradrpostnr', 'kommune_forradrpoststed', 'kommune_postadresse', '	kommune_ppostnr', 'kommune_ppoststed', 'kummune_telefon', 'kommune_kontaktinfo', 'kommune_kontaktinfo', 'kommune_hjemmeside'));
		
		$query->fields('B', array('innbygger', 'kommune_group'));
		$query->condition('A.kommune_id', $kommuneId, '=');
		$kommuneData = $query->execute();
		
		db_set_active();
		
		$kommuneId = $kommuneName = $kommuneMayor = $kommuneParti = $kommunePeriod = $kommuneAdv = $kommunePhone = $kommuneEmail = $kommuneUrl = NULL;
		
		$kommuneGroup = $innbyggerTotal = 0;
		
		foreach ($kommuneData as $dataRow) 
		{
			$kommuneId = $dataRow->kommune_id;
			$kommuneName = $dataRow->kommune_navn;
			$kommuneMayor = $dataRow->kommune_ordforer;
			$kommuneParti = $dataRow->kommune_parti;
			$kommunePeriod = $dataRow->kommune_periode;
			$kommuneAdv = $dataRow->kommune_adviser;
			$kommunePhone = $dataRow->kummune_telefon;
			$kommuneEmail = $dataRow->kommune_kontaktinfo;
			$kommuneUrl = $dataRow->kommune_hjemmeside;
			$innbyggerTotal = $dataRow->innbygger;
			$kommuneGroup = $dataRow->kommune_group;	
			
			$kommuneForretningsadr = $dataRow->kommune_forretningsadr;
			$kommuneForradrpostnr = $dataRow->kommune_forradrpostnr;
			$kommuneForradrpoststed = $dataRow->kommune_forradrpoststed;
			$kommunePostadresse = $dataRow->kommune_postadresse;
			$kommunePpostnr = $dataRow->kommune_ppostnr;
			$kommunePpoststed = $dataRow->kommune_ppoststed;			
		}	
				
		$logoPath = $base_url."/sites/default/files/komlogo/".$kommuneId.".gif";

		$output.= '<div class="getUrlData">';	
		
		$output.= '<div class="right-content">';
		$output.= '	<div class="logo-widget">';
		$output.= '		<img src="'.$logoPath.'" title="'.$kommuneName.'" width="75" />';
		$output.= '		<h1>'.$kommuneName.'</h1>';
		$output.= '	</div>';

		$output.= '	<h3>Offisiell informasjon</h3>';
		$output.= '	<div class="info-box fylke-result">';
		$output.= '		<div class="inner-box">';
		$output.= '			<label>';
		$output.= '				<span style="width:200px;"><strong>Ordf&oslash;rer:</strong></span>';
		$output.= '				<span>'.$kommuneMayor.' - '.$kommuneParti.' ( '.$kommunePeriod.' ) </span>';
		$output.= '			</label>';

		if($user->uid)
		{
			$output.= '			<label>';
			$output.= '				<span><strong>R&aring;dmann:</strong></span>';
			$output.= '				<span>'.$kommuneAdv.'</span>';
			$output.= '			</label>';
		}

		$output.= '			<label>';
		$output.= '				<span><strong>E-post:</strong></span>';
		$output.= '				<span><a href="mailto:'.$kommuneEmail.'">'.$kommuneEmail.'</a></span>';
		$output.= '			</label>';
		
		if($user->uid)
		{
			$output.= '			<label>';
			$output.= '				<span><strong>Telefon:</strong></span>';
			$output.= '				<span>'.$kommunePhone.'</span>';
			$output.= '			</label>';
		}

		$output.= '			<label>';
		$output.= '				<span><strong>Hjemmeside:</strong></span>';
		$output.= '				<span><a href="http://'.$kommuneUrl.'" target="_blank">'.$kommuneUrl.'</a></span>';
		$output.= '			</label>';
		
		$output.= '			<label>';
		$output.= '				<span><strong>Kommune nr:</strong></span>';
		$output.= '				<span>'.$kommuneId.'</span>';
		$output.= '			</label>';
		$output.= '			<label>';
		$output.= '				<span><strong>Innbyggere:</strong></span>';
		$output.= '				<span>'.$innbyggerTotal.' ('.$dataYear.')</span>';
		$output.= '			</label>';
		$output.= '		</div>';		
		
		$output.= '		<div class="inner-box">';
		
		$output.= '			<label>';
		$output.= '				<span style="width:200px;"><strong>Forretningsadresse: </strong></span>';
		$output.= '				<span>'.$kommuneForretningsadr.'</span>';
		$output.= '			</label>';
		
		$output.= '			<label>';
		$output.= '				<span><strong>Postnr./Poststed:</strong></span>';
		$output.= '				<span>'.$kommuneForradrpostnr.' / '.$kommuneForradrpoststed.'</span>';
		$output.= '			</label>';
		
		$output.= '			<label>';
		$output.= '				<span><strong>Postadresse:</strong></span>';
		$output.= '				<span>'.$kommunePostadresse.'</span>';
		$output.= '			</label>';
		
		$output.= '			<label>';
		$output.= '				<span><strong>Postnr./Poststed:</strong></span>';
		$output.= '				<span>'.$kommunePpostnr.' / '.$kommunePpoststed.'</span>';
		$output.= '			</label>';
		
		$output.= '		</div>';

		$output.= '	</div>';

		if($user->uid)
			$output.= getBranchesGrid($kommuneId, $dataYear, $kommuneName);

		$output.= '</div>';	
								
		return $output;
	
	}
	
	function getBranchesGrid($fkId, $dataYear, $kommuneName)
	{
	
		global $base_url;  


		db_set_active('kommunaldata');	
		
		// GET Data Last Year
		$query = db_select('group_leverandor_total', 'A');
		$query->fields('A', array('gl_kommune_id', 'gl_group', 'gl_group_name', 'gl_total_company', 'gl_total_revenue'));
		$query->condition('A.gl_kommune_id', $fkId);
		$query->condition('A.gl_data_year', $dataYear-1);	
		
		$arrFKGroupDataLastYear = $query->execute()->fetchAll();
		
		// Get Data Current Year
$query = db_select('group_leverandor_total', 'A');
		$query->fields('A', array('gl_group', 'gl_group_name', 'gl_total_company','gl_kommune_ingroup', 'gl_total_revenue'));
		$query->condition('A.gl_kommune_id', $fkId);
		$query->condition('A.gl_data_year', $dataYear);	
		$query->orderBy('A.gl_total_revenue', 'DESC');
		$query->range(0, 100);
		
		$arrFKGroupData = $query->execute()->fetchAll();
						
		db_set_active();
		
		$arrGroupDataLastYear = array();
		foreach($arrFKGroupDataLastYear as $arrRowData)
		{
			$arrGroupDataLastYear[$arrRowData->gl_group] = $arrRowData->gl_total_revenue;
		}
				
		$output.= '<h3>De 100 Hovedbransjer i '.$kommuneName.'</h3>';

		$output.= '<table class="table-view" cellpadding="0" cellspacing="0" width="100%">';
		$output.= '	<thead>';
		$output.= '		<tr>';
		$output.= '			<th width="30%">Hovedbransjer</th>';
		$output.= '			<th width="15%" class="rightalign">Kj&oslash;pt '.$dataYear.' <a href="#" data-toggle="tooltip" class="tooltipwhite" title="Kj&oslash;pt i 1000"><i class="fa fa-question-circle"></i></a></th>';
		$output.= '			<th width="15%" class="rightalign">Antall leverand&oslash;rer<a href="#" data-toggle="tooltip" class="tooltipwhite" title="Antall leverandører i bransjen."><i class="fa fa-question-circle"></i></a></th>';
		if($type == 'fylke'){
			$output.= '			<th width="15%" class="rightalign">Gj. snitt <a href="#" data-toggle="tooltip" class="tooltipwhite" title="Gj. snittlig innkj&oslash;p fra fylker. Bel&oslash;p i hele 1000"><i class="fa fa-question-circle"></i></a></th>';
		}else{
			$output.= '			<th width="15%" class="rightalign">Gj. snitt <a href="#" data-toggle="tooltip" class="tooltipwhite" title="Gj. snittlig innkj&oslash;p fra kommuner av samme st&oslash;rrelse. Bel&oslash;p i hele 1000"><i class="fa fa-question-circle"></i></a></th>';
		}
		$output.= '			<th width="10%" class="rightalign">Endring (%) <a href="#" data-toggle="tooltip" class="tooltipwhite" title="Endring i % fra '.($dataYear-1). '"><i class="fa fa-question-circle"></i></a></th>';
		$output.= '		</tr>';
		$output.= '	</thead>';
		$output.= '<tbody>';
		
		if(!empty($arrFKGroupData))
		{
						
			$num = 1;
			foreach($arrFKGroupData as $arrGroupData)
			{
			
				//////////////////////////////////////////////////////////

				db_set_active('kommunaldata');	

				$query = db_select('group_data_by_fk_ingroup', 'A');
				$query->fields('A', array('ig_total_revenue', 'ig_total_company'));
				$query->condition('A.ig_group', $arrGroupData->gl_group);
				$query->condition('A.ig_kommune_ingroup', $arrGroupData->gl_kommune_ingroup);
				$query->condition('A.ig_data_year', $dataYear);	
		
				$arrGroupInGroupData = $query->execute()->fetchAll();

				db_set_active();

				$groupAverage = 0;

				foreach ($arrGroupInGroupData as $ingroup) {
					$groupAverage = $ingroup->ig_total_revenue/$ingroup->ig_total_company;
				}

				//////////////////////////////////////////////////////////
				
				$groupTotalInvoiceCurrYear = $arrGroupData->gl_total_revenue;
				$groupIncreasePersentage =  round((($arrGroupData->gl_total_revenue - $kommuneDataLastYear[$arrGroupData->gl_group]) / ($arrGroupData->gl_total_revenue + $kommuneDataLastYear[$arrGroupData->gl_group]) ) * 100, 0);
								
				//$bgcolor = ($num % 2 === 0) ? 'class="rowBackground"' : NULL;

				$output.= '<tr>';
				$output.= '	<td><a href="'.$base_url.'/groupdatacard/'.$arrGroupData->gl_group.'/'.$dataYear.'" target="_blank">'.$num.' - '.$arrGroupData->gl_group_name.'</a></td>';
				$output.= '	<td class="rightalign">'.numberFormat($groupTotalInvoiceCurrYear/1000, 0).'</td>';
				$output.= '	<td class="rightalign">'.$arrGroupData->gl_total_company.'</td>';
				$output.= '	<td class="rightalign">'.numberFormat($groupAverage/1000, 0).'</td>';
				$output.= '	<td class="rightalign">'.$groupIncreasePersentage.' %</td>';
				$output.= '</tr>';
				$num++;				
			}
		}

		$output.= '	</tbody>';
		$output.= ' </table> ';
		
		return $output;
	}
	
	
	