<?php
header('X-Frame-Options: GOFORIT'); 
function cross_promotion_main_industries_menu() {
    $items = array();

    $items['cross_promotion_main_industries/main_industries'] = array(
        'title' => '',
        'page callback' => 'main_industries_record',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function main_industries_record($kommuneId, $dataYear,$fkId,$kommuneName) {
   global $base_url;
    global $user;
    $kommuneId = $_GET['var1'];
    $kommuneName = $_GET['name'];
    $dataYear = $_GET['var2'];
    $fkId = $_GET['var3'];
    $output = NULL;
    db_set_active('kommunaldata');	
			
		// GET Data Last Year
    
		$query = db_select('leverandor_data', 'A');
		$query->fields('A', array('ld_orgnr', 'ld_revenue'));
		$query->condition('A.ld_kommune_id', $fkId);
		$query->condition('A.ld_data_year', ($dataYear-1));		
		
		if(!empty($supplierId))
			$query->condition('A.ld_orgnr', ($supplierId) , 'IN');	
		
		if(!empty($strGroupClass))
			$query->condition('A.ld_group', ($strGroupClass) , 'IN');	
		
		if(!empty($strSubsectorClass))
			$query->condition('A.ld_subclass', ($strSubsectorClass) , 'IN');	
		
		if(!empty($nMinRavenu) AND $nMinRavenu > 0)
			$query->condition('A.ld_revenue', $nMinRavenu, '>=');	

		if(!empty($nMaxRavenu) AND $nMaxRavenu > 0)
			$query->condition('A.ld_revenue', $nMaxRavenu, '<=');	
			
		$query->orderBy('A.ld_revenue', 'DESC');
		
		$arrkommuneSupplierDataLastYear = $query->execute()->fetchAll();
		
		// Get Data Current Year
		$query = db_select('leverandor_data', 'A');
		$query->fields('A', array('ld_orgnr', 'ld_orgnavn', 'ld_group','ld_group_name', 'ld_subclass', 'ld_subclass_name', 'ld_revenue'));
		$query->condition('A.ld_kommune_id', $fkId);
		$query->condition('A.ld_data_year', $dataYear);	
		
		if(!empty($supplierId))
			$query->condition('A.ld_orgnr', ($supplierId) , 'IN');	
		
		if(!empty($strGroupClass))
			$query->condition('A.ld_group', ($strGroupClass) , 'IN');	
		
		if(!empty($strSubsectorClass))
			$query->condition('A.ld_subclass', ($strSubsectorClass) , 'IN');	
		
		if(!empty($nMinRavenu) AND $nMinRavenu > 0)
			$query->condition('A.ld_revenue', $nMinRavenu , '>=');	

		if(!empty($nMaxRavenu) AND $nMaxRavenu > 0)
			$query->condition('A.ld_revenue', $nMaxRavenu , '<=');	
					
		$query->orderBy('A.ld_revenue', 'DESC');
		$query->range(0, 10);
		
		$arrkommuneSupplierData = $query->execute()->fetchAll();
				
		db_set_active();
		
		$kommuneDataLastYear = array();
		foreach($arrkommuneSupplierDataLastYear as $arrRowData)
		{
			$kommuneDataLastYear[$arrRowData->ld_orgnr] = $arrRowData->ld_revenue;
                        //$kommuneName = $arrRowData->kommune_navn;
		}

		////////////////////////////////////////////////////////////////////////////////
                $logoPath = $base_url."/sites/default/files/komlogo/".$fkId.".gif";
		
		$output.= '<div class="right-content">';
		$output.= '	<div class="logo-widget" style="margin-left:0px;">';
		$output.= '		<img src="'.$logoPath.'" title="'.$kommuneName.'" width="75" />';
		$output.= '		<h1>'.$kommuneName.'</h1>';
		$output.= '	</div>';
		 
		$output.= '<center><h3>Hovedbransjer i '.$kommuneName.'</h3></center>';
		if($type == 'kommune'){
			$output.= '<i>Tabellen under viser de 10 hovedbransjene (innenfor s&oslash;kekriteriene) i ' .$kommuneName. ' i ' .$dataYear. '. Samt gjennomsnittlig innkjøp for kommuner i samme størrelse i hver hovedbransje</i>';
		}else{
			$output.= '<i>Tabellen under viser de 10 hovedbransjene (innenfor s&oslash;kekriteriene) i ' .$kommuneName. ' i ' .$dataYear. '. Samt gjennomsnittlig innkjøp for fylker i hver hovedbransje</i>';
		}
		$output.= '<table class="table-view" cellpadding="0" cellspacing="0" width="100%">';
		$output.= '	<thead>';
		$output.= '		<tr>';
		$output.= '			<th width="30%">Hovedbransjer</th>';
		$output.= '			<th width="15%" class="rightalign">Kj&oslash;pt '.$dataYear.' <a href="#" data-toggle="tooltip" class="tooltipwhite" title="Kj&oslash;pt i 1000"><i class="fa fa-question-circle"></i></a></th>';
		$output.= '			<th width="15%" class="rightalign">Antall leverand&oslash;rer<a href="#" data-toggle="tooltip" class="tooltipwhite" title="Antall leverandører i bransjen."><i class="fa fa-question-circle"></i></a></th>';
		if($type == 'fylke'){
			$output.= '			<th width="15%" class="rightalign">Gj. snitt <a href="#" data-toggle="tooltip" class="tooltipwhite" title="Gj. snittlig innkj&oslash;p fra fylker. Bel&oslash;p i hele 1000"><i class="fa fa-question-circle"></i></a></th>';
		}else{
			$output.= '			<th width="15%" class="rightalign">Gj. snitt <a href="#" data-toggle="tooltip" class="tooltipwhite" title="Gj. snittlig innkj&oslash;p fra kommuner av samme st&oslash;rrelse. Bel&oslash;p i hele 1000"><i class="fa fa-question-circle"></i></a></th>';
		}
		$output.= '			<th width="10%" class="rightalign">Endring (%) <a href="#" data-toggle="tooltip" class="tooltipwhite" title="Endring i % fra '.($dataYear-1). '"><i class="fa fa-question-circle"></i></a></th>';
		$output.= '		</tr>';
		$output.= '	</thead>';
		$output.= '	<tbody>';
		

		db_set_active('kommunaldata');	


		// Get Data Last Year
		$query = db_select('group_leverandor_total', 'A');
		$query->fields('A', array('gl_kommune_id', 'gl_group', 'gl_group_name', 'gl_total_company', 'gl_total_revenue'));
		$query->condition('A.gl_kommune_id', $fkId);
		$query->condition('A.gl_data_year', $dataYear-1);	
				
		if(!empty($strGroupClass))
			$query->condition('A.gl_group', ($strGroupClass) , 'IN');	
		
		if(!empty($nMinRavenu) AND $nMinRavenu > 0)
			$query->condition('A.gl_total_revenue', $nMinRavenu , '>=');	

		if(!empty($nMaxRavenu) AND $nMaxRavenu > 0)
			$query->condition('A.gl_total_revenue', $nMaxRavenu , '<=');	
					
		$query->orderBy('A.gl_total_revenue', 'DESC');
		
		$arrKommuneGroupDataLastYear = $query->execute()->fetchAll();
		
		$groupDataLastYear = array();
		foreach($arrKommuneGroupDataLastYear as $arrRowData)
		{
			$groupDataLastYear[$arrRowData->gl_group] = $arrRowData->gl_total_revenue;
		}  
		
		// Get Data Current Year
		/* SQL
			select gl_group, gl_group_name, gl_total_company, gl_total_revenue
			from tbl_group_leverandor_total
			where gl_kommune_id = 602 and gl_data_year = 2013
			order by gl_total_revenue desc
			limit 10
		*/
		$query = db_select('group_leverandor_total', 'A');
		$query->fields('A', array('gl_group', 'gl_group_name', 'gl_kommune_ingroup', 'gl_total_company', 'gl_total_revenue'));
		$query->condition('A.gl_kommune_id', $fkId);
		$query->condition('A.gl_data_year', $dataYear);	
				
		if(!empty($strGroupClass))
			$query->condition('A.gl_group', ($strGroupClass) , 'IN');	
		
		if(!empty($nMinRavenu) AND $nMinRavenu > 0)
			$query->condition('A.gl_total_revenue', $nMinRavenu , '>=');	

		if(!empty($nMaxRavenu) AND $nMaxRavenu > 0)
			$query->condition('A.gl_total_revenue', $nMaxRavenu , '<=');	
					
		$query->orderBy('A.gl_total_revenue', 'DESC');
		$query->range(0, 10);
		
		$arrkommuneGroupData = $query->execute()->fetchAll();
				
		db_set_active();
		
						
		if(!empty($arrkommuneSupplierData))
		{
			$num = 1;
			foreach($arrkommuneGroupData as $arrGroupData)
			{

				//////////////////////////////////////////////////////////

				db_set_active('kommunaldata');	

				$query = db_select('group_data_by_fk_ingroup', 'A');
				$query->fields('A', array('ig_total_revenue', 'ig_total_company'));

				$query->condition('A.ig_group', $arrGroupData->gl_group);
				$query->condition('A.ig_kommune_ingroup', $arrGroupData->gl_kommune_ingroup);
				$query->condition('A.ig_data_year', $dataYear);	
		
				$arrGroupInGroupData = $query->execute()->fetchAll();

				db_set_active();

				$groupAverage = 0;

				foreach ($arrGroupInGroupData as $ingroup) {
					$groupAverage = $ingroup->ig_total_revenue/$ingroup->ig_total_company;
				}

				//////////////////////////////////////////////////////////
			
				$groupTotalInvoiceCurrYear = $arrGroupData->gl_total_revenue;
			
				$groupIncreasePersentage =  round((($arrGroupData->gl_total_revenue - $groupDataLastYear[$arrGroupData->gl_group]) / ($arrGroupData->gl_total_revenue + $groupDataLastYear[$arrGroupData->gl_group]) ) * 100, 0);
								
				$output.= '<tr>';

				$output.= '	<td><a href="'.$base_url.'/groupdatacard/'.$arrGroupData->gl_group.'/'.$dataYear.'" target="_blank">'.$num.' - '.$arrGroupData->gl_group_name.' <span class="glyphicon glyphicon-link" aria-hidden="true"></span></a></td>';

				$output.= '	<td class="rightalign">'.numberFormat($groupTotalInvoiceCurrYear/1000, 0).'</td>';
								
				$output.= '	<td class="rightalign">'.$arrGroupData->gl_total_company.'</td>';
				
				$output.= '	<td class="rightalign">'.numberFormat($groupAverage/1000, 0).'</td>';

				$output.= '	<td class="rightalign">'.$groupIncreasePersentage.' %</td>';

				$output.= '</tr>';
				
				$num++;
			}			
		}

		$output.= '	</tbody>';
		$output.= ' </table> ';	
		$output.= '</br><a href="'.$base_url.'/topgroups/'.$fkId.'/'.$dataYear.'/'.$type.'" target="_blank"><strong>(Vis de 100 st&oslash;rste bransjene ette innkj&oslash;p)</strong></a></br>';		
		
		return $output;
}